# run built image and nats server in docker
version: '3.7'

services:
  go-app:
    image: go-app
    container_name: go-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1323:1323"
    environment:
      - NATS_URL=nats://nats-server:4222
      - DOMAIN=<your domain>
    depends_on:
      - nats-server
    networks:
      - go-app-network
  
  nats-server:
    image: nats:latest
    container_name: nats-server
    command: ["--js"]
    ports:
      - "4222:4222"
    networks:
      - go-app-network

networks:
  go-app-network:
    name: go-app-network
